export const PALAVRAS_RUINS = new Set([
 "crescimento",
"inovação",
 "liderança",
 "estratégia",
 "inteligência",
 "criatividade",
 "desafio",
 "transformação",
 "poder",
 "autenticidade",
 "empatia",
 "resiliência",
 "colaboração",
 "aprendizado",
 "diversidade",
"conhecimento",
 "visão",
 "impacto",
 "eficiência",
 "produtividade",
 "motivação",
 "conquista",
"resultados",
 "sustentabilidade",
 "empoderamento",
 "ética",
"responsabilidade",
 "inclusão",
 "tecnologia",
 "conexão",
 "saber",
 "autodescoberta",
 "segurança",
 "parceria",
 "desempenho",
 "autonomia",
 "visibilidade",
 "bem-estar",
 "planejamento",
 "produtividade",
 "crescer",
"futuro",
 "valores",
"soluções",
"qualidade",
 "agilidade",
 "aprendizado contínuo",
"expansão",
 "identidade",
 "comprometimento",
 "experiência",
 "aceleração",
 "desenvolvimento",
"esforço",
 "capacidade",
 "satisfação",
 "compaixão",
"qualidade de vida",
 "conscientização",
 "ética profissional",
 "gestão",
 "desafios",
 "objetivos",
 "crescimento pessoal",
"efetividade",
 "iniciativa",
 "ajuda",
 "pensamento crítico",
"otimismo",
 "satisfação do cliente",
 "sistemas",
 "reconhecimento",
"inclusão social",
 "trabalho em equipe",
 "perseverança",
 "motivação interna",
 "cultura organizacional",
 "resultados mensuráveis",
 "ajustamento",
 "inteligência emocional",
 "compromisso",
 "inovação tecnológica",
 "eficácia",
 "estratégia de marketing",
 "tomada de decisão",
 "proatividade",
 "colaboração interdepartamental",
 "recursos humanos",
 "habilidades",
 "valorização",
 "sucesso",
 "experiência do usuário",
 "adaptabilidade",
 "colaboração internacional",
 "tendências",
 "sistemas ágeis",
 "desafios do futuro",
 "revolução digital",
 "inteligência artificial",
 "empreendedorismo" ,
]);